Fix check version

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -17,13 +17,18 @@ check_version:
   image: ubuntu:24.04
 
   script:
-    - echo "Checking version consistency..."
-    - "VERSION_IN_CODE=$(grep -oP 'project\\(.*VERSION\\s+\\K[0-9]+\\.[0-9]+\\.[0-9]+' CMakeLists.txt)"
-    - "TAG_VERSION=${CI_COMMIT_TAG#v}"
-    - echo "CMake version: $VERSION_IN_CODE"
-    - echo "Tag version: $TAG_VERSION"
-    - "if ! echo \"$CI_COMMIT_TAG\" | grep -Eq '^v[0-9]+\\.[0-9]+\\.[0-9]+$'; then echo \"ERROR: Invalid tag format\"; exit 1; fi"
-    - "if [ \"$VERSION_IN_CODE\" != \"$TAG_VERSION\" ]; then echo \"ERROR: Version mismatch!\"; exit 1; fi"
+    - |
+      echo "Checking version consistency..."
+
+      VERSION_IN_CODE=$(grep "project(" CMakeLists.txt | sed -E 's/.*VERSION[[:space:]]+([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
+      TAG_VERSION=${CI_COMMIT_TAG#v}
+
+      echo "CMake version: $VERSION_IN_CODE"
+      echo "Tag version: $TAG_VERSION"
+
+      echo "$CI_COMMIT_TAG" | grep -Eq '^v[0-9]+\.[0-9]+\.[0-9]+$' || { echo "ERROR: Invalid tag format"; exit 1; }
+
+      [ "$VERSION_IN_CODE" = "$TAG_VERSION" ] || { echo "ERROR: Version mismatch!"; exit 1; }
 
   rules:
     - if: '$CI_COMMIT_TAG'
